version: '2'

services:
  hadoopbase:
    build: ./hadoop-base
    image: dynamicheart/hadoop-base:1.0.0-hadoop2.7.6-java8
    container_name: hadoopbase
  hadoopmaster:
    build: ./hadoop-master
    image: dynamicheart/hadoop-master:1.0.0-hadoop2.7.6-java8
    container_name: hadoopmaster
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - hadoopbase
      - hadoopslave1
      - hadoopslave2
      - hadoopslave3
    volumes:
      - hadoopmaster_name:/hadoop/dfs/name
    ports:
      - 8088:8088
    stdin_open: true
    tty: true
  hadoopslave1:
    build: ./hadoop-slave
    image: dynamicheart/hadoop-slave:1.0.0-hadoop2.7.6-java8
    container_name: hadoopslave1
    stdin_open: true
    tty: true
    depends_on:
      - hadoopbase
    volumes:
      - hadoopslave1_data:/hadoop/dfs/data
    ports:
      - 8040:8042
    stdin_open: true
    tty: true
  hadoopslave2:
    build: ./hadoop-slave
    image: dynamicheart/hadoop-slave:1.0.0-hadoop2.7.6-java8
    container_name: hadoopslave2
    depends_on:
      - hadoopbase
    volumes:
      - hadoopslave2_data:/hadoop/dfs/data
    ports:
      - 8041:8042
    stdin_open: true
    tty: true
  hadoopslave3:
    build: ./hadoop-slave
    image: dynamicheart/hadoop-slave:1.0.0-hadoop2.7.6-java8
    container_name: hadoopslave3
    depends_on:
      - hadoopbase
    volumes:
      - hadoopslave3_data:/hadoop/dfs/data
    ports:
      - 8042:8042
    stdin_open: true
    tty: true

volumes:
  hadoopmaster_name:
  hadoopslave1_data:
  hadoopslave2_data:
  hadoopslave3_data:
